### ISSUE TITLE
configuration fails when using fallback

### ISSUE THREAD

**Issue by andreaTP** [unicredit/shocon#5]
A couple of examples are here:
https://github.com/unicredit/shocon/tree/fallbackFail

one problem is probably in the parser that doesn't split keys on "." character.
the other is in the resolution of fallback ...probably...

**Comment by evacchi** [comment]
will look into it

**Comment by evacchi** [comment]
I think this is now fixed. We need more test cases, though (e.g. Arrays) but tests now pass.
I've split the test case you gave into two and added a few more.
Now:

- fallback uses a stack of `shocon.Config.Object`
- when a `shocon.Config.Object` is parsed the `shocon.Config.Object.fromPairs()` routine is used. This transforms flat keys of the form `foo.bar.baz` into nested trees of Objects and then merges the trees by key.

**Comment by andreaTP** [comment]
this should be closed
